### PR TITLE
Add `toCatchable` interpreter to `quasar.effect.Failure`

### PR DESCRIPTION
**Pull request by jedesah**

### CODE REVIEW

**Comment by wemrysi** [comment]
Good idea. How about deleting `toTaskFailure` and reimplementing `toRuntimeException` using `toCatchable` as it is more general?

Also, why not `bugfix` as this doesn't modify the public (HTTP) api?

**Comment by jedesah** [comment]
I figured maybe `toTaskFailure` was there for inference purposes.

I didn't realize we had changed our naming scheme for version bumps.

**Comment by jedesah** [comment]
Why did we change the naming scheme? It's not a bug fix, I prefered `revision`.

**Comment by wemrysi** [comment]
I don't think `toTaskFailure` exists for inference purposes, I just didn't think to implement `toCatchable`. 

As for the naming scheme, see https://github.com/slamdata/devtools/pull/9.

**Comment by jedesah** [comment]
@wemrysi Implemented suggestions.

**Comment by wemrysi** [comment]
:+1:

**Pull request closed without merging**
