### PR TITLE
Autojoin filter when the predicate isn't freemappable from the source

### PR DESCRIPTION
**Pull request by alissapajer**
Fixes https://github.com/quasar-analytics/quasar/issues/2366

Completes part of https://github.com/quasar-analytics/quasar/issues/3021

### CODE REVIEW

**Comment by wemrysi** [comment]
@alissapajer Looks like even _more_ tests are passing ;)

**Comment by alissapajer** [comment]
@wemrysi hm, so `demo/nestedSelectWithReduce.test` didn't pass on the previous build, but passed on this build for spark and ML. I can't get it to pass locally either though; it's returning results but incorrect ones. It's very strange that it passed for four connectors this last build. If it's going to be flaky, then unfortunately I think we have to `skip` it :/

**Comment by wemrysi** [comment]
@alissapajer Oh, bummer 😞

**Comment by alissapajer** [comment]
@wemrysi this is ready to go!

**Pull request merged**
