### PR TITLE
handle upload of zip archive to directory path

### PR DESCRIPTION
**Pull request by mossprescott**
So that downloading with GET and then uploading with PUT recreates a directory (or notebook).

### CODE REVIEW

**Comment by jdegoes** [comment]
@mossprescott Does this support saving / restoring views, which are used extensively in workbooks?

**Comment by mossprescott** [comment]
This isn't doing anything special for views. I have the impression that workspaces will recreate their views when they're evaluated, somewhat confirmed by my testing, but I was hoping to get more clarity when someone looks at slamdata/slamdata/issues#1143.

**Comment by drostron** [comment]
Only a minor comment. LGTM. Up to you whether or not you want to make a change.

**Comment by mossprescott** [comment]
Thanks for the feedback, which I will incorporate.

Given ongoing discussion, I'm putting this in progress and will address #1618 here.

**Comment by jdegoes** [comment]
@drostron Handing this over to you for now.

**Comment by jdegoes** [comment]
@drostron Don't let this one die.

**Comment by drostron** [comment]
@jdegoes For sure. It's at the top of my queue after our connectors release this week.

**Comment by jedesah** [comment]
Superseded by #1883

**Pull request closed without merging**
