### PR TITLE
pull out core functionality from main so it can be reused in other projects

### PR DESCRIPTION
**Pull request by jdegoes**

### CODE REVIEW

**Comment by jdegoes** [comment]
@jr Can you review / merge?

**Comment by jedesah** [comment]
LGTM. Just missing a changelog.

**Comment by jedesah** [comment]
(called `revision.md` since it's not changing the REST API)

**Comment by jdegoes** [comment]
@jedesah Done. This shouldn't affect build success / failure so please merge when you can.

**Comment by jedesah** [comment]
Ok. Looks good. I don't see any problem with merging before CI finishes. You need to merge in `master` though for the `merge` script to work.

**Comment by jdegoes** [comment]
@jedesah Done.

**Pull request merged**
