### PR TITLE
Increased travis_wait timeout. This is a good idea.

### PR DESCRIPTION
**Pull request by djspiewak**
There is no way I will regret this.

### CODE REVIEW

**Comment by alissapajer** [comment]
Mandatory :scream:

**Comment by nicflores** [comment]
@djspiewak,
What travis/build error is this suppose to fix?

**Comment by alissapajer** [comment]
@nicflores this is "fixing" the travis timeouts we get while compiling `connector`. I'm going to break `connector` into subprojects because the compile times are out of hand, but this is still fine to land imo.

**Comment by nicflores** [comment]
Thanks @alissapajer. Merging...

**Comment by rintcius** [comment]
Hmm, isn't this supposed to avoid build failures like https://travis-ci.org/quasar-analytics/quasar/jobs/365050824 ?
Looks like the property was set, but still terminating the build after 10 mins:

```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

**Pull request merged**
