### PR TITLE
Decrease coverage minimum for `connector`

### PR DESCRIPTION
**Pull request by jedesah**

### CODE REVIEW

**Comment by drostron** [comment]
Going to keep this in a short term holding pattern. @alissapajer has a few tests in mind that might get us back within the current coverage threshold.

**Comment by jedesah** [comment]
Cool! That would be ideal. I was (decided to just copy paste the code in QA) in a rush to get a new build of quasar published to maven central.

**Comment by drostron** [comment]
@jedesah Ah. We should still be publishing to GitHub releases and sonatype upon #1 passing which latest master builds are — coverage is now on another Job.

**Comment by alissapajer** [comment]
We can close this since we are disabling codecov on travis #2153.

**Comment by drostron** [comment]
Closing per https://github.com/quasar-analytics/quasar/pull/2138#issuecomment-299256546

**Pull request closed without merging**
