### PR TITLE
Merge master into next-major

### PR DESCRIPTION
**Pull request by alissapajer**

### CODE REVIEW

**Comment by jsantos17** [comment]
This is the PR that disabled the Marklogic tests: https://github.com/quasar-analytics/quasar/pull/2632/files

**Comment by alissapajer** [comment]
@jsantos17 ah interesting. `next-major` already had the commits from that PR. But somehow the `union.test` didn't get updated. I'll add a separate commit to this PR to disable it for `marklogic_xml`.

I also checked and all the other tests that were disabled for ML in that PR _are_ disabled already in `next-major`. So updates to `union.test` just got lost in the previous merge.

**Comment by alissapajer** [comment]
Ooo awesome, for spark we have:
```
[error] x select reduction from nested select [./demo/nestedSelectWithReduce.test] (2 seconds, 896 ms)
[error]  Fixed now, you should remove the 'pendingUntilFixed' marker (QuasarSpecification.scala:75)
```
I'll push a change enabling that!

**Comment by alissapajer** [comment]
@jsantos17 this should be good to go now!

**Pull request merged**
