### PR TITLE
Attempt to limit the MarkLogic docker instance's memory usage.

### PR DESCRIPTION
**Pull request by wemrysi**

### CODE REVIEW

**Comment by wemrysi** [comment]
@nicflores So it is encouraging that both of the MarkLogic jobs for this PR passed on the first try, but that may just be 🎲 smiling upon us. Anyhow, hopefully this reduces the memory pressure by MarkLogic, time will tell I guess.

**Comment by nicflores** [comment]
@wemrysi, this looks great! Thanks for the PR. I'm working on caching the download of the marklogic rpm on another branch that I hope to PR soon. I'm having issues getting tests to pass for marklogic in the build of said branch. I may base my branch off the changes in this PR in order go get those tests to pass.

**Comment by wemrysi** [comment]
@nicflores or you could just merge this ;)

**Comment by alissapajer** [comment]
Should this PR close the issue https://github.com/quasar-analytics/quasar/issues/2241?

**Comment by wemrysi** [comment]
@alissapajer I hope so, but I think we need to run with this for a few days to see if things actually improve.

**Comment by wemrysi** [comment]
@alissapajer Or, if you prefer, I can re-run this PR's build a few times and see how it goes.

**Comment by alissapajer** [comment]
I'd be fine merging this PR, then after a few days if the ML builds aren't having memory problems, we can close the issue.

**Comment by wemrysi** [comment]
@nicflores @alissapajer Either of you want to merge this?

**Comment by nicflores** [comment]
yeah, I'll go ahead and merge

**Pull request merged**
