### PR TITLE
Newlines in tests.

### PR DESCRIPTION
**Pull request by paulp**
This is effectively the same PR as #1294, which I closed accidentally.

### CODE REVIEW

**Comment by sellout** [comment]
Happy to merge as soon as tests pass.

**Comment by paulp** [comment]
@sellout the tests passed [over at my parallel universe](https://travis-ci.org/paulp/quasar/builds/151041115).

**Comment by sellout** [comment]
This one’s missing a changelog 😕

**Comment by mossprescott** [comment]
@sellout: any reason not to merge this now?

**Pull request merged**
