### PR TITLE
Add integration test for non-equi join

### PR DESCRIPTION
**Pull request by jedesah**

### CODE REVIEW

**Comment by rintcius** [comment]
@jedesah should be green after merging in the new master

**Comment by rintcius** [comment]
ping @jedesah - can you merge from master to make travis happy?

**Comment by rintcius** [comment]
@jedesah `marklogic_json` is working according to Travis (ran it twice). Did you see it fail?

**Comment by jedesah** [comment]
@rintcius Nope. Just had copied over that from another join test. Removed the pending

**Pull request merged**
