### PR TITLE
Delete moar

### PR DESCRIPTION
**Pull request by alissapajer**
Delete some more dead code in mimir and friends.

### CODE REVIEW

**Comment by alissapajer** [comment]
appveyor passed and then reported thread errors. I wish I knew how to make it stop doing that.

**Comment by djspiewak** [comment]
@alissapajer I wonder if something is actually wrong.  AppVeyor usually isn't unreliable; I suspect the build is actually just failing on windows.

**Comment by alissapajer** [comment]
@djspiewak appveyor passed on #3346, which contains this PR. So if something is actually wrong, it's not consistently wrong.

**Comment by alissapajer** [comment]
And according to the printout all the tests have passed, so whatever component is failing, it's not the tests themselves (or compilation).

**Pull request merged**
