### PR TITLE
Fixed broken rounding of bigdecimal values

### LINKED ISSUE #2674: Figure out why floor/ceil/trunc aren't working in mimir
They delegate to well-tested functions, and they pass the `StdLibSpec`, so… wut??  The integration tests clearly show results which are non-integer values.

### PR DESCRIPTION
**Pull request by djspiewak**
Fixes #2674

### CODE REVIEW

**Comment by djspiewak** [comment]
@edmundnoble If you're 👍 on this, please merge.

**Comment by edmundnoble** [comment]
I'm getting:
```
$ devtools/bin/sdmerge quasar/quasar-analytics 2845
error: quasar/quasar-analytics#2845 has already been merged
```

**Comment by alissapajer** [comment]
@edmundnoble it should be `quasar-analytics/quasar`. But yeah that error message is super unhelpful.

**Comment by djspiewak** [comment]
Yeah the error is buggy.  One thing that helps is you don't have to specify the repository if your current working directory is any branch of the quasar git repo (locally).

**Comment by edmundnoble** [comment]
Gotcha. Thanks to both of you.

**Pull request merged**
