### PR TITLE
Remove need for QUASAR_HOME

### PR DESCRIPTION
**Pull request by rabbitonweb**
Part of https://github.com/quasar-analytics/quasar/issues/1712 & https://github.com/quasar-analytics/quasar/issues/1907

This change brings two unrelated functionalities
1. Remove need for QUASAR_HOME
2. Handle more gracefully errors when user tries to connect second spark based connector

Ad. 1 Remove need for QUASAR_HOME
Every spark based connector need to know where `sparkcore.jar` is placed. Previously that information was provided with `QUASAR_HOME` env. variable. Now the need for `QUASAR_HOME` is completely removed. ill Path of quasar-web.jar as a root to find sparkcore.jar

Ad.2 Handle errors

When running Spark only one `SparkContext` per JVM is possible. Thus if we try to connect a second spark-based connector, we will get an error. It caused not human-friendly error message on UI. Now we fail with more detailed message, hiding the details.

### CODE REVIEW

**Comment by rabbitonweb** [comment]
@drostron after recent commit generation of `SparkContext` is unified among all spark based connectors

**Comment by drostron** [comment]
Also, there's still a reference to `QUASAR_HOME` in `README.md`.

**Comment by drostron** [comment]
@rabbitonweb Needs a merge from master

**Comment by drostron** [comment]
@rabbitonweb Needs a semantic version label

**Pull request merged**
