### PR TITLE
QScript

### PR DESCRIPTION
**Pull request by alissapajer**

### CODE REVIEW

**Comment by alissapajer** [comment]
In progress PR of QScript. There are a handful of outstanding `TODO`s. I figure now would be a good time to start looking at the diff in its entirety.

**Comment by alissapajer** [comment]
@sellout the build is green now (3/4 passed, with `MetadataServiceSpec` the culprit). I resolved many of the TODO's, including `Traverse`, `Equal` and `Show` for `MapFunc`, `digForBucket` impl complete, `NameGen` used instead of the same `String` everywhere, among other things. I also made the normalization-requiring tests `pending` for the time being so we can merge. Let me know if there is anything else low-hanging that's blocking the merge.

**Comment by sellout** [comment]
I think this is good to go.

**Comment by alissapajer** [comment]
@sellout great! I'll get this in shortly!

**Comment by alissapajer** [comment]
I'm going to give better commit messages to my commit blocks as well :)

**Pull request closed without merging**
