### PR TITLE
`it/testing.conf` as `.example`

### PR DESCRIPTION
**Pull request by drostron**

### CODE REVIEW

**Comment by alissapajer** [comment]
@drostron do we want to add `it/testing.conf` to `.gitignore`? (I'm fine with a [skip ci] commit).

**Comment by alissapajer** [comment]
@drostron also, this will need a PR description before it can be merged.

**Comment by drostron** [comment]
@alissapajer Yes, good to have `it/testing.conf` in `.gitignore` and was put in place prior to this PR. The descriptive " " has been added to please our merge script.

**Comment by alissapajer** [comment]
@drostron Ah, so it looks like the `.gitignore` file is incorrect. It has `/it/testing.conf` when it should have `it/testing.conf`, which is why the file wasn't getting ignored before this PR.

**Comment by drostron** [comment]
Perhaps unexpectedly, a leading `/` for paths in `.gitignore` are relative to the `.gitignore` location. Also, I verified earlier that `it/testing.conf` is ignored after this update. The reason it wasn't ignored before this update was due to being tracked.

**Pull request merged**
