### PR TITLE
Revert enter fix

### PR DESCRIPTION
**Pull request by djspiewak**
😞

### CODE REVIEW

**Comment by jedesah** [comment]
LGTM. Will see what the build server thinks

**Comment by djspiewak** [comment]
@jedesah Given that we're in a hurry, I would consider this safe to merge once we've seen the unit tests and the mimir integration tests pass.

**Comment by alissapajer** [comment]
Why is this being reverted?

**Comment by djspiewak** [comment]
@alissapajer It breaks running quasar inside of docker. And travis, because travis is docker.

**Comment by alissapajer** [comment]
We should reopen https://slamdata.myjetbrains.com/youtrack/issue/qz-3378 when this lands.

**Comment by djspiewak** [comment]
@alissapajer Yeah. @jedesah is also presently working on a fix that we think will address the issue.

**Pull request merged**
