### PR TITLE
Disallow mounting mimir on relative paths

### PR DESCRIPTION
**Pull request by edmundnoble**
I did this by accident from the runner and that was *very* odd. @djspiewak says this is never a valid thing to do in general.

### CODE REVIEW

**Comment by edmundnoble** [comment]
A session where I attempt to mount to a relative path:
```
$ curl -v -X PUT http://localhost:8080/mount/fs/mimir/target/ -d '{ "mimir": { "connectionUri":"tmp/precog/" } }'
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> PUT /mount/fs/mimir/target/ HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Length: 46
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 46 out of 46 bytes
< HTTP/1.1 400 Invalid mount configuration.
< Content-Type: application/json; charset=UTF-8
< Date: Fri, 16 Feb 2018 19:14:10 GMT
< Content-Length: 132
<
* Connection #0 to host localhost left intact
{ "error": { "status": "Invalid mount configuration.", "detail": { "reasons": [ "Mimir cannot be mounted to a relative path" ] } } }%
```

**Comment by alissapajer** [comment]
Needs version label.

**Comment by edmundnoble** [comment]
Failure looks spurious.

**Comment by djspiewak** [comment]
@edmundnoble For the record, when there's a spurious failure, you should restart the job (after noting down the error and ensuring a ticket is creating).  We generally don't want to merge PRs with red builds; if the failure truly is spurious, then the restart will make it go green, and the ticket will track the work to move to a more stable build.

**Pull request merged**
