### PR TITLE
Queries and modules now support imports with `/../`

### LINKED ISSUE #2430: Support `/../` in import paths

### PR DESCRIPTION
**Pull request by jedesah**
- Fixes #2430 
- Add a few more tests around importing

### CODE REVIEW

**Comment by jsantos17** [comment]
@jedesah would you mind giving me some background on this? Is there an issue with more information I can check? I don't understand why we're implementing this feature.

**Comment by jedesah** [comment]
@jsantos17 It's somewhat related to #2418 and the fact that `/../` is required to reference a sibling module right now although that is subject to change depending on the outcome of the discussion on that issue.

But even in isolation, I don't see a good reason to prohibit this kind of path in an import statement. It's sort of an oversight on my part to not have included it in the initial implementation.

**Comment by jedesah** [comment]
@jsantos17 I think this is blocking @natefaubion. If you could have a look this evening or perhaps first thing tmr morning.

**Comment by jsantos17** [comment]
Is this ready to merge @jedesah or are you planning to add more commits?

**Comment by jedesah** [comment]
@jsantos17 Btw, I'm curious why you asked me if there were more commits coming? Did I miss a new step in the PR process?

**Pull request merged**
