### PR TITLE
It tests refactor

### PR DESCRIPTION
**Pull request by rabbitonweb**
Part of #3313

### CODE REVIEW

**Comment by rabbitonweb** [comment]
Reassigning bcs @alissapajer is OOO

**Comment by djspiewak** [comment]
So the names of the tests that you moved got pretty universally changed to a space-free, semi-mangled encoding.  Is there a particular reason for that?  The names are meant to be human-friendly, so there's no reason to mangle them.

**Comment by rabbitonweb** [comment]
@djspiewak actually in other branch I'm unifying those names like that - it's actually for a reason to be able to run a batch of tests prefixed with given phrase. Whitespaces makes it problematic (too many tests run when actually is needed). Does it make sense?

**Comment by rabbitonweb** [comment]
@djspiewak I in future want to rename it to `demo_games_step1.test`, so
1. when I want to run all demo tests I do

```it/testOnly **.StreamingQueryRegressionSpec -- -ex demo -```
2. whenI want to run all "games" tests I do

```it/testOnly **.StreamingQueryRegressionSpec -- -ex demo_games_step --```

**Comment by wemrysi** [comment]
@rabbitonweb Could we maybe "tag" similar issues with a key, but keep the human readable names e.g. `[demo_games] Some nice description for a person.`?

**Comment by wemrysi** [comment]
Or maybe we add a `group` key to the test metadata and when we convert the test into a specs2 example, we "tag" the test using the group key automatically, when present. This would keep them as data, which would be nice.

**Comment by rabbitonweb** [comment]
@wemrysi I might go with "tag" first and then maybe in the futue do the second thing you proposed

**Comment by rabbitonweb** [comment]
@djspiewak @wemrysi Are you gusy ok with keeping this order I propse in folder structure:

```
|-demo
|-regression
|-qa
   |-s01
   |-s02
```
?

**Comment by rabbitonweb** [comment]
@djspiewak if I "tag" and bring whitespaces back, will this be 👍 ?

**Comment by djspiewak** [comment]
@rabbitonweb Yep!

**Comment by rabbitonweb** [comment]
I'm closing this and I will open new PR with more changes because this is already too old and I dont want to backport those changes

**Pull request closed without merging**
