### PR TITLE
Revert change to example h2 config

### PR DESCRIPTION
**Pull request by jedesah**

### CODE REVIEW

**Comment by jedesah** [comment]
@garyb Sorry I didn't catch this earlier. We still support `file` for backwards compatibility but will use `location` moving forward since we now support any h2 url (apparently you can connect to remote h2 installations)

**Comment by alissapajer** [comment]
I was under the impression that `location` doesn't currently work, while `file` does. Should `location` currently work?

**Comment by garyb** [comment]
@alissapajer I've just re-tested with the latest Quasar and `location` is acceptable in the config now. I guess I must have caught it in between when the PR was merged for the change and when a release was made with it working!

Sorry @jedesah :smile:

**Comment by garyb** [comment]
I also was able to use `mem:` for my H2 database location, which is what I wanted to do in the first place when I "discovered" this :)

**Comment by jedesah** [comment]
@garyb No worries! 😄

**Pull request merged**
