### PR TITLE
Upgrade Spark to latest version 2.1.0

### PR DESCRIPTION
**Pull request by rabbitonweb**
Upgrade Spark to latest version 2.1.0

### CODE REVIEW

**Comment by jedesah** [comment]
You don't need the `revision.md` anymore. Can you get rid of that commit, no one is depending on this PR so you can force push to remove it.

**Comment by rabbitonweb** [comment]
@jedesah this PR was merged with latest master, I think we can upgrade Spark

**Comment by jedesah** [comment]
Why does it say there are no changes?

**Comment by jedesah** [comment]
Also, don't forget to update [this](https://github.com/quasar-analytics/quasar/blob/master/project/Dependencies.scala#L77) version to be in sync with Spark

**Comment by jedesah** [comment]
We don't want to upgrade anymore?

**Comment by rabbitonweb** [comment]
@jedesah I'm running `sbt compile` right now on fresh branch. Will close this PR with link to the new one

**Comment by rabbitonweb** [comment]
Duplicated by https://github.com/quasar-analytics/quasar/pull/1908

**Pull request closed without merging**
