### PR TITLE
sort single value reduction

### LINKED ISSUE #2750: `select count(*) from x order by y` yields broken queries in new Mongo
For example, 

`SELECT COUNT(*) AS cnt FROM /mngo/jps/zips ORDER BY cnt DESC` results in Mongo throwing an exception.

whereas 

`SELECT COUNT(*) as cnt FROM /mngo/jps/zips` yields the correct `db.zips.count()` plan

Discovered as part of #2667.

### PR DESCRIPTION
**Pull request by rintcius**
Fixes #2750

### CODE REVIEW

**Comment by rintcius** [comment]
Note: there's also a similar piece of code for binary reductions, which may also have this problem: https://github.com/quasar-analytics/quasar/blob/master/connector/src/main/scala/quasar/qscript/Transform.scala#L372-L379

However the only binary reduction is `UnshiftMap` of which there seems to be no usage and I don't know how to test this. If someone knows an example I can add a test.

**Comment by alissapajer** [comment]
@rintcius can you add a unit test for this query over in https://github.com/quasar-analytics/quasar/blob/master/connector/src/test/scala/quasar/qscript/QScript.scala? Even if the qscript isn't ideal yet, it would be good to track it.

**Comment by alissapajer** [comment]
@rintcius you can generate `UnshiftMap` directly with `select {state : pop ...} from zips` (and `UnshiftArray` as `select [pop ...] from zips`). Mongo 3.4 doesn't have `UnshiftMap` implemented, and I'm actually not sure if any connectors do. (As a side note, you can work backwards from [the parser](https://github.com/quasar-analytics/quasar/blob/master/frontend/src/main/scala/quasar/sql/parser.scala#L334) to figure out how to manually generate certain nodes.)

Additionally we create `UnshiftMap` over in [`ShiftRead`](https://github.com/quasar-analytics/quasar/blob/master/connector/src/main/scala/quasar/qscript/ShiftRead.scala#L73) but then elide the `UnshiftMap` over in [`Coalesce`](https://github.com/quasar-analytics/quasar/blob/master/connector/src/main/scala/quasar/qscript/Coalesce.scala#L359) when we can. So any query where the `UnshiftMap` wasn't elided in that way would also contain one.

If no connectors have `UnshiftMap` implemented, you could still write a qscript unit test for it and verify the provenance by manually verifying the qscript.

**Comment by alissapajer** [comment]
Also, I'm actually a bit surprised that no other integration tests came to life with this fix.

**Comment by jsantos17** [comment]
Might be worth checking other queries with `count(*)` in the [unit tests](https://github.com/quasar-analytics/quasar/blob/master/mongodb/src/test/scala/quasar/physical/mongodb/planner.scala#L1462). Some tests might be fixed but still marked as pending because of different generated names or something else irrelevant.

**Comment by alissapajer** [comment]
@jsantos17 :+1: good idea, any non-bucketed reduction would fall into this case.

**Comment by rintcius** [comment]
@alissapajer Updated binary reduction as well. And added unit tests for both unary and binary reduction.

The problem I had regarding `UnshiftMap` was more semantically than syntactically. Anyway, with the unit test it's now at least tracked.

@jsantos17 @alissapajer Regarding the tests in `mongodb/planner`, I went through those queries already - and went through them again just now - but none of them seem to be affected by this fix.  However let me know if I missed one.

**Comment by jsantos17** [comment]
@rintcius sad to hear that's the case. I'll give it sometime later today.

**Pull request merged**
