### PR TITLE
Ensure new reduce name is used when remapping dimensions in MinimizeAutoJoins

### PR DESCRIPTION
**Pull request by wemrysi**
Previously, we were remapping the dimensions using the name of the `Map` node around the new `Reduce`, which resulted in incorrect bucket access.

### CODE REVIEW

**Comment by djspiewak** [comment]
PlannerSpec

**Comment by wemrysi** [comment]
Looks like this is blocked on #3198 for the provenance normalization.

**Comment by djspiewak** [comment]
Needs merge from master.

**Comment by wemrysi** [comment]
@djspiewak `master` merged, also improved provenance normalization a bit.

**Pull request merged**
