### PR TITLE
Refactor Planner

### PR DESCRIPTION
**Pull request by rabbitonweb**
This is just merely refactoring `Planner.scala` into smaller files each holding one of the `Planner` instance.

Part of https://github.com/quasar-analytics/quasar/issues/1659

### CODE REVIEW

**Comment by rabbitonweb** [comment]
@sellout have u seen this? :)

**Comment by sellout** [comment]
Needs a version label.

**Comment by sellout** [comment]
I just added it for you – it’s the label that tells the merge script how to increment the semver. It has to be on every PR.

**Comment by rabbitonweb** [comment]
Thx, I was 100% sure I've added it this time... 😞

**Pull request merged**
