### PR TITLE
Bring spark back

### LINKED ISSUE #2800: Reenable Spark in master
This entails fixing the following three things:

- [x] Propagate the stupid context classloader stuff through to whatever Netty is doing
- [x] Ensure that no other areas are similarly problematic
- [ ] Make the `sparkcore` project publish two assembly JARs during publication: with and without the Spark dependency
  + Also make the spark assembly JARs match the naming convention of the other connectors while we're at it

Once all of this is done, we can reenable Spark publication in `build.sbt` as well as in `scripts/publishJar`.

### PR DESCRIPTION
**Pull request by rabbitonweb**
Fixes #2800

### CODE REVIEW

**Comment by rabbitonweb** [comment]
This PR brings `spark-local` and `spark-hdfs` back!

Other connectors (`spark-elstic` and `spark-cassandra`) will be back once their interpreters will be fixed (dealing with eventual consistency).

@drostron this PR is ready for review

**Comment by rabbitonweb** [comment]
@drostron can you have a look today?

**Comment by drostron** [comment]
@rabbitonweb For sure — planning on it.

**Comment by djspiewak** [comment]
Note: this doesn't reenable publication of Spark.  I'll open a separate ticket for that.  It's somewhat tricker than it seems, since we have to create *two* separate assembly JARs.

**Comment by djspiewak** [comment]
Requires merge with master.

**Pull request merged**
