### PR TITLE
Utilize `=` instead of `like` for files

### PR DESCRIPTION
**Pull request by drostron**
Hopefully this will alleviate some of the connection timeouts seen in Travis.

### CODE REVIEW

**Comment by mossprescott** [comment]
Guess that wasn't it.

**Comment by drostron** [comment]
Yeah, more hope than reason on this attempt. Looks like times for `quasar.fs.*` were similar with and without this change too.

**Comment by mossprescott** [comment]
I'm going to merge this since it seems like a good idea anyway, even if it doesn't fix the flaky build. I'll restart that last one just to give it a chance to build cleanly before I do that.

And I would rather have this running in Travis even it's not 100% stable, especially since only @dave is running CB locally as far as I know.

**Comment by mossprescott** [comment]
Arg. Should have reloaded the page before commenting. I'm OK with that as well, and I concur on the times not looking better.

**Pull request closed without merging**
