### PR TITLE
Use TTypes in the qscript tests and in Transform.

### PR DESCRIPTION
**Pull request by alissapajer**

### CODE REVIEW

**Comment by paulp** [comment]
THIS MAKES ME VERY HAPPY

**Comment by alissapajer** [comment]
@paulp `TTypes` is very nice :)

**Comment by paulp** [comment]
@alissapajer wait until you see FGTypes!

**Comment by paulp** [comment]
I reassigned to myself because I feel qualified to pass judgment on this commit.

**Pull request merged**
