### PR TITLE
Fix JSON format of flattenNestedMap.test

### PR DESCRIPTION
**Pull request by jsantos17**
#qz-3783 done

### CODE REVIEW

**Comment by djspiewak** [comment]
TIL @djspiewak doesn't understand JSON syntax.

**Comment by alissapajer** [comment]
@jsantos17 `flattenNestedMap.test` came to life for mimir so that's cool? I don't understand how it has been passing for other connectors previously though. Errors are being swallowed in strange scary ways.
```
[error]     x flatten a map inside a field projection [./flattenNestedMap.test] (183 ms)
[error]      Fixed now, you should remove the 'pendingUntilFixed' marker (QuasarSpecification.scala:77)
```
And then a couple other tests are actually just failing now. And I don't have an explanation for this yet...
```
[error]     x nestedreductionsonnull [./demo/nestedreductionsonnull.test] (40 seconds, 531 ms)
[error]      ; Actual result does not match expected value. 
[error]      
[error]       Diff: 
[error]       Obj
[error]      ╰─ Map
[error]         ├─ Key("parallel")
[error]         │  ╰─ Null
[error]         ├─ Key("measure")
[error]         │  ╰─ Dec(116.0)
[error]         ├─ Key("stack")
[error]         │  ╰─ Str("female")
[error]         ╰─ Key("category")
[error]            ├─ >>> Str("ABERDEEN PROVING GROUND")
[error]            ╰─ <<< Str("ABERDEEN") 
```

**Comment by jsantos17** [comment]
@alissapajer me neither. Not sure what's going on. Confirming master is green locally at the moment. Will report back.

**Comment by alissapajer** [comment]
Yeah, if this diff is actually what caused the other tests to fail, then the error reporting from our integration test suite is quite messed up. :scream:

**Comment by jsantos17** [comment]
Interestingly, without this change, the test suite doesn't run locally. 😱

**Comment by jsantos17** [comment]
@djspiewak @alissapajer 

So it looks like we had some real failures unreported because of the invalid JSON. Looks like the test suite gets to the test with invalid JSON, fails and then the build is green. Fixing the JSON uncovered the other problems.

I'm not sure I follow the meaning behind the null-related tests, but Mongo is not return the expectations. Hence marked as `pending`.

**Comment by alissapajer** [comment]
:+1: I created https://slamdata.myjetbrains.com/youtrack/issue/qz-3779 to track these two failing `null`-related tests.

@jsantos17 do you have evidence that the integration tests that were supposed to run _after_ the json parsing failed were run at all? Or I wonder, did we just silently give up on all subsequent tests after the json parsing failed?

**Comment by jsantos17** [comment]
@alissapajer still investigating. I'll report back when I get some more info. Looks like `postgres` was silently failing a bunch of tests too. Hence the red build. We really need to audit the test suite to prevent this kind of problems in the future.

**Comment by jsantos17** [comment]
@alissapajer with regard to your question: I don't think we were running *any* tests due to the failure to parse JSON. 

It seems to me that even green builds skipped the test suite.

Check out these two logs for green builds:

https://api.travis-ci.org/v3/job/364626419/log.txt
https://api.travis-ci.org/v3/job/364626423/log.txt

I don't see the test suite running in either of them.

**Comment by alissapajer** [comment]
@jsantos17 I looked a those builds and I agree :scream:

**Comment by alissapajer** [comment]
Confirmed that `StreamingQueryRegressionSpec` is running for the integration test jobs.

**Pull request merged**
