### PR TITLE
Avoid creating unnecessary autojoins.

### PR DESCRIPTION
**Pull request by sellout**
Many more ThetaJoins are avoided in QScript with this.

This is based on #1514.

### CODE REVIEW

**Comment by alissapajer** [comment]
@sellout conflict in the revision.md

**Comment by sellout** [comment]
Ok, fixed and updated.

**Comment by alissapajer** [comment]
One build failed with
```
[error] (marklogicValidation/compile:compileIncremental) java.lang.NoClassDefFoundError: scala/reflect/internal/Trees
[error] (foundation/compile:compileIncremental) java.lang.NoClassDefFoundError: scala/reflect/internal/Trees
```

**Comment by alissapajer** [comment]
On a different PR I saw
```
[error] (marklogicValidation/compile:compileIncremental) sbt.InvalidScalaInstance: Scala instance doesn't exist or is invalid: 
[error]     version 2.11.8, library jar: /home/travis/.ivy2/cache/org.typelevel/scala-library/jars/scala-library-2.11.8.jar, compiler jar: /home/travis/.ivy2/cache/org.typelevel/scala-compiler/jars/scala-compiler-2.11.8.jar
[error] (foundation/compile:compileIncremental) sbt.InvalidScalaInstance: Scala instance doesn't exist or is invalid: 
[error]     version 2.11.8, library jar: /home/travis/.ivy2/cache/org.typelevel/scala-library/jars/scala-library-2.11.8.jar, compiler jar: /home/travis/.ivy2/cache/org.typelevel/scala-compiler/jars/scala-compiler-2.11.8.jar
```
These are both new errors, as far as I've seen.

**Pull request merged**
