### PR TITLE
Somehow marklogic_json got a pass on this one...

### PR DESCRIPTION
**Pull request by djspiewak**
Fixes the build issues we've been seeing with marklogic_json

### CODE REVIEW

**Comment by djspiewak** [comment]
Failed due to the flaky (and I'm relatively certain not-commutative) `Monoid[TableModel]`.  This was already filed as #3162.  I'll disable the test in a different PR.

**Comment by jsantos17** [comment]
Will merge once green.

**Comment by jsantos17** [comment]
Apparently it passed again and that's why Travis is red

**Comment by djspiewak** [comment]
Yeah it's flaky. I'm just going to skip that test on all connectors, since for the most part, they just timeout.

**Comment by djspiewak** [comment]
@jsantos17 Can you merge this?

**Pull request merged**
