### PR TITLE
Switch CoreEffIORW from CoM to expanded Coproducts

### PR DESCRIPTION
**Pull request by drostron**
Isolated compilation of `RestApi.coreServices[CoreEffIORW]` went from ~130s down
to ~40s on a 2015 macbook pro

### CODE REVIEW

**Comment by drostron** [comment]
Towards speeding up downstream compilation leading to build timeouts slamdata/slamdata-backend#280

**Comment by jedesah** [comment]
We can never have nice things... 😞

**Comment by jedesah** [comment]
Just missing a version bump

**Comment by jedesah** [comment]
I'm going to merge this as is because I want to compilation speedup and that way it will be available to SB sooner but I think a comment would be a good idea so it doesn't revert back to nicer/slower syntax

**Comment by drostron** [comment]
@jedesah Comment added

**Pull request merged**
