### PR TITLE
Change spark-local connectionUri

### PR DESCRIPTION
**Pull request by rabbitonweb**
spark-local should always use "local[*]", thus the user only needs to
provide path to folder from local file system

### CODE REVIEW

**Comment by rabbitonweb** [comment]
Part of https://github.com/quasar-analytics/quasar/issues/1899

**Comment by drostron** [comment]
Looks like `.travis.yml` needs a corresponding update.

**Comment by rabbitonweb** [comment]
It's... SATURDAY! :)

**Comment by drostron** [comment]
😀

**Pull request merged**
