### PR TITLE
Newlines in tests.

### PR DESCRIPTION
**Pull request by paulp**
I may be missing something fundamental but when analyzing test
failures I find this sort of presentation...
```
  [info]
  [info] containsAtLeast should
  [info]   + match exact result with no dupes  + match shuffled result with no dupes  + reject shuffled fields  + fail if the process fails  + match with any additional (no dupes)  + reject with any missing (no dupes)containsExactly should
  [info]   + match exact result with no dupes  + match shuffled result with no dupes  + reject shuffled fields  + fail if the process fails  + reject with any additional (no dupes)  + reject with any missing (no dupes)equalsExactly should
  [info]   + match exact result  + reject shuffled result  + reject shuffled fields  + fail if the process fails  + reject with any additional  + reject with any missingequalsInitial should
  [info]   + match exact result  + reject shuffled result  + reject shuffled fields  + fail if the process fails  + match with any following  + reject with any leadingdoesNotContain should
  [info]   + reject exact result with no dupes  + reject shuffled result with no dupes  + reject shuffled fields  + fail if the process fails  + reject any subset  + match any disjoint values
```

...quite a bit less readable than this sort.

```
  [info] containsAtLeast should
  [info]   + match exact result with no dupes
  [info]   + match shuffled result with no dupes
  [info]   + reject shuffled fields
  [info]   + fail if the process fails
  [info]   + match with any additional (no dupes)
  [info]   + reject with any missing (no dupes)
  [info] containsExactly should
  [info]   + match exact result with no dupes
  [info]   + match shuffled result with no dupes
  [info]   + reject shuffled fields
  [info]   + fail if the process fails
  [info]   + reject with any additional (no dupes)
  [info]   + reject with any missing (no dupes)
  [info] equalsExactly should
  [info]   + match exact result
  [info]   + reject shuffled result
  [info]   + reject shuffled fields
  [info]   + fail if the process fails
  [info]   + reject with any additional
  [info]   + reject with any missing
  [info] equalsInitial should
  [info]   + match exact result
  [info]   + reject shuffled result
  [info]   + reject shuffled fields
  [info]   + fail if the process fails
  [info]   + match with any following
  [info]   + reject with any leading
  [info] doesNotContain should
  [info]   + reject exact result with no dupes
  [info]   + reject shuffled result with no dupes
  [info]   + reject shuffled fields
  [info]   + fail if the process fails
  [info]   + reject any subset
  [info]   + match any disjoint values
```

### CODE REVIEW

**Comment by wemrysi** [comment]
@paulp Thanks! I agree and had no idea what caused the presentation to change (I think we upgraded specs and one point and the newlines disappeared all of a sudden).

LGTM.

**Comment by jedesah** [comment]
I had no idea about that...

Agreed. I think it's more readable with new lines. I will admit though that scrolling the Travis build logs is already a nightmare as is!

**Comment by sellout** [comment]
We used to have everything serialized, because we had things that broke otherwise. But then we narrowed that down and fixed most of the issues. When we switched to parallelized runs, it started printing oddly, but I figured specs2 just wasn't serializing printing correctly. But I guess they have a distinct interface for that?

**Comment by paulp** [comment]
Oops, I didn't mean to delete the branch.

**Pull request closed without merging**
