### PR TITLE
[SD-1042] Ready/remove java property

### PR DESCRIPTION
**Pull request by jedesah**

### CODE REVIEW

**Comment by jedesah** [comment]
@sellout Can you have a look at this? Should take about 30 seconds to review :smile:

**Comment by sellout** [comment]
I already did … but apparently never submitted my comment(?). I did update the label, though.

**Comment by jedesah** [comment]
Ah, ya what's the protocol again? we comment because there is no way to get notified of a label change?

Anyway, thx for reviewing! :smile:

**Comment by sellout** [comment]
Yeah, exactly.

**Pull request merged**
