### PR TITLE
Add normalize function for Free

### PR DESCRIPTION
**Pull request by jedesah**

### CODE REVIEW

**Comment by wemrysi** [comment]
@jedesah Could you give (or link to) some motivation for this function? Curious as to what sort of situations one would use it in.

**Comment by wemrysi** [comment]
Reposting the motivation here for completeness: https://github.com/slamdata/quasar-advanced/pull/12/files#diff-f42ccc5a52742c3ac48baf1630279c0aR44

**Comment by wemrysi** [comment]
Given `quasar.fp.pointNT` is `normalize` necessary?

**Comment by jedesah** [comment]
@wemrysi I don't believe it is necessary anymore. Thx for pointing out the alternative!

**Pull request closed without merging**
