### PR TITLE
Reduced compile time for connector project.

### PR DESCRIPTION
**Pull request by paulp**

### CODE REVIEW

**Comment by sellout** [comment]
Travis really doesn’t want to build this PR.

**Comment by paulp** [comment]
@sellout If it helps, it's green [over here](https://travis-ci.org/paulp/quasar/builds/163457046).

**Comment by alissapajer** [comment]
+1 to merge

**Comment by alissapajer** [comment]
@sellout the build "over there" is good enough for me. You?

**Comment by alissapajer** [comment]
@paulp all the builds failed with actual compile errors. Is this build then different than the one you linked to?

**Comment by alissapajer** [comment]
@paulp @sellout I need to merge this in to my work locally now since there are going to be merge conflicts, so I can work on this compile issue locally and submit you a PR fixing it.

Unless you're already working on it, in which case I'll wait.

**Comment by paulp** [comment]
@alissapajer Sorry, was at lunch. Not working on it yet, but I'll fix it if you like.

**Comment by paulp** [comment]
But no, this build is exactly the one which passed the tests.

**Comment by paulp** [comment]
@alissapajer Ugh, I take it back. I could probably spend a whole day on these three lines and still not be able to determine the meaning. Why must things be this complicated?
```scala
    def toQScript(lp: Fix[LogicalPlan]) = {
      val lc: DiscoverPath.ListContents[FileSystemErrT[PhaseResultT[Free[S, ?],?],?]] =
        (adir: ADir) => EitherT(listContents(input, adir).liftM[PhaseResultT])
      for {
        qs <- (QueryFile.convertToQScriptRead[Fix, FileSystemErrT[PhaseResultT[Free[S, ?],?],?], QScriptRead[Fix, ?]](lc)(lp)).map(transFutu(_)(ShiftRead[Fix, QScriptRead[Fix, ?], SparkQScript].shiftRead(idPrism.reverseGet)(_)).transCata(optimize.applyAll))
        _ <- EitherT(WriterT[Free[S, ?], PhaseResults, FileSystemError \/ Unit]((Vector(PhaseResult.Tree("QScript (Spark)", qs.render) : PhaseResult), ().right[FileSystemError]).point[Free[S, ?]]))
      } yield qs
    }
```

**Comment by alissapajer** [comment]
@paulp my plan is always to ascribe as many types as possible and hope it figures something out

**Comment by paulp** [comment]
@alissapajer Yeah, that's usually my plan, but I've already been sitting here guessing incorrect types for way too long.

**Comment by alissapajer** [comment]
Yeah, I got caught up in something else and haven't looked at it yet, but I will.

**Comment by alissapajer** [comment]
@paulp hooray!

**Comment by paulp** [comment]
It's hopeless at travis. Until the jar downloading issue is resolved, these tests will never pass.

**Comment by sellout** [comment]
We seem to be getting jobs that actually complete now (and pretty durned quickly, too!)

I think once this is merged, we can remove `travis_wait`, too.

**Pull request merged**
