### PR TITLE
Upgrade Spark to `2.0.2`

### PR DESCRIPTION
**Pull request by jedesah**

### CODE REVIEW

**Comment by jedesah** [comment]
@rabbitonweb This should be a really easy review 😄

**Comment by rabbitonweb** [comment]
@jedesah i was about to upgrade to 2.1.0 :)  Can we change that to 2.1.0?

**Comment by jedesah** [comment]
Since the build on this one is green, I think it would better to merge this one and then open a new PR to upgrade to `2.1.0`. In this case, if the `2.1.0` PR gets in very soon, it won't change much, but I think in general it's best to try and be as incremental as possible on these things.

**Comment by rabbitonweb** [comment]
We should upgrade to latest Spark 2.1.0 - especially since they've added one feature we were missing on our demo environment.
@jedesah I've added you as reviewer there https://github.com/quasar-analytics/quasar/pull/1870

**Comment by rabbitonweb** [comment]
We should upgrade to latest Spark 2.1.0 - especially since they've added one feature we were missing on our demo environment.
@jedesah I've added you as reviewer there #1870

**Pull request closed without merging**
