### PR TITLE
Revert "A Refined Port"

### PR DESCRIPTION
**Pull request by drostron**
To avoid non-deterministic build failures including fthomas/refined#260

### CODE REVIEW

**Comment by drostron** [comment]
@wemrysi Ready for a look

**Comment by wemrysi** [comment]
@drostron Oh, one thing, don't we need to update the version?

**Comment by wemrysi** [comment]
Oh wait, sorry, thought this was advanced for whatever reason, nevermind.

**Comment by wemrysi** [comment]
Looks like this might require a merge from `master` as the merge script complains it can't fast-forward. :disappointed:

**Comment by drostron** [comment]
Destined to address build failures seen there at least 🙂

Ah, merge incoming...

**Comment by drostron** [comment]
@wemrysi Ready

**Pull request merged**
