### PR TITLE
Wip/tightening q script types

### PR DESCRIPTION
**Pull request by alissapajer**
This PR is a clone of #1427. Some builds on that PR are hanging after 10 minutes, so this PR extends the build timeout to 20 minutes to see if we still see the hangs.

### CODE REVIEW

**Comment by alissapajer** [comment]
Ok, this _might_ be the solution. The postgres build passed and the 2.6 mongo build failed with OOM, which is at least not a hang... I'm running both those builds again checking for build consistency.

**Comment by alissapajer** [comment]
@sellout ok, so with a 240 min timeout, we consistently run out of memory in the 2.6 mongo build.

https://travis-ci.org/quasar-analytics/quasar/jobs/161169649

**Comment by alissapajer** [comment]
If this works it would address #1405.

**Comment by alissapajer** [comment]
OOM trace: https://gist.github.com/alissapajer/cc29e5c424b4b1452b1b0bc24bcc59d6

**Comment by sellout** [comment]
So, that OOM is interesting – it’s happening in scaladoc generation. Scaladoc has been a pain in many ways. This is just one more. I wonder if we can generate less (e.g., only for the connector, frontend, and interface projects) or what. It’d be nice to move it to a separate build, but 1. it needs to be in the same place as the rest of the jar and 2. we don’t want to publish the jar if we don’t have at least one connector passing integration tests.

**Comment by alissapajer** [comment]
closing - hopefully solved with #1459

**Pull request closed without merging**
