### PR TITLE
Faster keyvaluestore implementation

### PR DESCRIPTION
**Pull request by jedesah**

### CODE REVIEW

**Comment by jedesah** [comment]
This PR is based on #1681. I still need to add a `revision.md` that is appropriate for the changes in this PR.

**Comment by jedesah** [comment]
This is ready for review now

**Comment by drostron** [comment]
Was there a particular usage that was slow and motivated this? If so, did you notice an improvement?

**Comment by drostron** [comment]
@jedesah just a minor comment and a quick question.

**Comment by jedesah** [comment]
Sorry. Forgot about this. No particular usage that was slow. Just kind of always bugged me that the default implementation was a sequential one. i.e. that concurrent threads need to wait for each other even if they are dealing with separate keys. This new default implementation should not suffer from this problem. I don't have any proof that it's faster in practice though.

**Comment by drostron** [comment]
Context appreciated. 👍🏼

**Comment by jedesah** [comment]
Oh, I was actually going to change that `exactly` thing you mentioned 😄

**Comment by drostron** [comment]
Ah, too quick on the trigger. I'm ok with it either way 😄.

**Pull request merged**
