### PR TITLE
add travis wait 30 to aws s3 cache download

### PR DESCRIPTION
**Pull request by rintcius**
see #3570

### CODE REVIEW

**Comment by nicflores** [comment]
@rintcius, we might as well also add a `travis_timeout` to the cleanup stage.

**Comment by rintcius** [comment]
@nicflores ok, done

**Comment by nicflores** [comment]
@rintcius, lets put one here too:
https://github.com/quasar-analytics/quasar/pull/3572/files#diff-354f30a63fb0907d4ad57269548329e3R148

**Comment by nicflores** [comment]
@rintcius, looks good. I'll merge when the build succeeds.

**Pull request merged**
