### PR TITLE
Add ability to ignore field order in query regression tests

### PR DESCRIPTION
**Pull request by drostron**
- Enable trivial.test against Couchbase

Merge after: #1563

### CODE REVIEW

**Comment by sellout** [comment]
Looks good – will merge when green.

**Comment by sellout** [comment]
If you have time to kill (😉) you could switch more `select *` queries to use this.

**Comment by drostron** [comment]
Heh, true. I figure Couchbase will motivate that transition as those queries are enabled against it.

**Comment by mossprescott** [comment]
This is missing revision.md, otherwise I would be ready to merge it.

**Pull request merged**
