### PR TITLE
Add `Typecheck` derived function to QScript

### PR DESCRIPTION
**Pull request by jedesah**

### CODE REVIEW

**Comment by djspiewak** [comment]
@rintcius can assist in fixing up the planner specs for this change, which should make the unit tests pass.

**Comment by rintcius** [comment]
Looks like there's something that needs to be fixed in non-test code also. Many tests fail with:
`'Left(QScriptPlanningFailed(InternalError(unimplemented TypeCheck expression,None)))' is not Right `.

@jedesah Let me know if I can help with that as well.

**Comment by djspiewak** [comment]
@jedesah What's the current status on this?

**Comment by jedesah** [comment]
@djspiewak It's blocked on https://slamdata.myjetbrains.com/youtrack/issue/qz-3330 which I'm waiting for https://github.com/quasar-analytics/quasar/pull/3367 to be merged before resuming. I could base my work of the PR, but I've got the `PlannerSpec` issue and the wrong error message for a mount move issues to do anyway in the meantime

**Comment by djspiewak** [comment]
Gotcha. Sounds good.

**Comment by alissapajer** [comment]
@jedesah what's the status of this? Should we pass it off to someone else to finish up or is this something you'll be finishing up?

**Comment by jedesah** [comment]
If it's not super urgent, I'm happy to work on it as part of my 10 hours a month. Otherwise, I think @rintcius would be a good candidate for picking it up as we've talked about this issue together

**Comment by djspiewak** [comment]
@jedesah I'm going to close this for now as a general housekeeping thing.  If someone else picks it up, they'll probably start with this branch and I'll make sure you're aware.  Otherwise, it's still somewhere on your pile of fun.  :-)

**Pull request closed without merging**
