### PR TITLE
Delete spark and postgres connectors

### PR DESCRIPTION
**Pull request by alissapajer**

### CODE REVIEW

**Comment by alissapajer** [comment]
Looks like I removed too much stuff related to the quasar metastore posgres. Fixing.

**Comment by alissapajer** [comment]
@wemrysi I'd rather we have a clean history for this sort of mass deletion. Are you :+1: if I rebase this PR so that the travis problems were having are fixed where they should have been fixed rather than as a separate commit after the fact?

**Comment by wemrysi** [comment]
@alissapajer Absolutely, :+1:!

**Comment by alissapajer** [comment]
@wemrysi build is green, ready for review.

**Pull request merged**
