### PR TITLE
assumeReadType across Branches and apply to Sort

### LINKED ISSUE #3014: Improve mongo's assumeReadType
Currently mongo's rewrite step `assumeReadType` does not traverse across branches which leads to queries doing type-checks unnecessarily. 

Moreover, this rewrite is not traversing `Sort` nodes, also leading to unnecessary type-checks.

In both cases queries may end up doing map-reduce because of these checks.

### PR DESCRIPTION
**Pull request by rintcius**
Fixes #3014

* make `Trans` monadic and use it for `assumeReadType`
* apply `assumeReadType` to `Sort` nodes

Relates to #2884 - this brings some tests onPar and simplifies some others, but does not avoid MR for all `Sort`s

### CODE REVIEW

**Comment by djspiewak** [comment]
Looks like all of the mongodb jobs failed.

**Comment by rintcius** [comment]
Yeah there's a failing integration test - looking into that

**Comment by rintcius** [comment]
The query that fails now was before running on MR. 

<details>
<summary>Query output</summary>

```
QScript Mongo (Prefer Projection):
Subset(Take)
├─ Unreferenced
├─ From
│  ╰─ Sort
│     ├─ Filter
│     │  ├─ ShiftedRead(/test/zips, ExcludeId)
│     │  ╰─ Guard
│     │     ├─ ProjectField
│     │     │  ├─ ○
│     │     │  ╰─ Constant(Str(loc))
│     │     ├─ Type(FlexArr(0, None, Top))
│     │     ├─ Guard
│     │     │  ├─ ProjectIndex
│     │     │  │  ├─ ProjectField
│     │     │  │  │  ├─ ○
│     │     │  │  │  ╰─ Constant(Str(loc))
│     │     │  │  ╰─ Constant(Int(1))
│     │     │  ├─ Type(Int, Dec, Interval, Str, Timestamp, Date, Time, or Bool)
│     │     │  ├─ Guard
│     │     │  │  ├─ ProjectField
│     │     │  │  │  ├─ ○
│     │     │  │  │  ╰─ Constant(Str(pop))
│     │     │  │  ├─ Type(Int, Dec, Interval, Str, Timestamp, Date, Time, or Bool)
│     │     │  │  ├─ Lt
│     │     │  │  │  ├─ ProjectField
│     │     │  │  │  │  ├─ ○
│     │     │  │  │  │  ╰─ Constant(Str(pop))
│     │     │  │  │  ╰─ ProjectIndex
│     │     │  │  │     ├─ ProjectField
│     │     │  │  │     │  ├─ ○
│     │     │  │  │     │  ╰─ Constant(Str(loc))
│     │     │  │  │     ╰─ Constant(Int(1))
│     │     │  │  ╰─ Undefined
│     │     │  ╰─ Undefined
│     │     ╰─ Undefined
│     ├─ Bucket
│     │  ╰─ List
│     ╰─ Order
│        ╰─ Ascending
│           ╰─ By
│              ╰─ ProjectField
│                 ├─ ○
│                 ╰─ Constant(Str(_id))
╰─ Count
   ╰─ Map
      ├─ Unreferenced
      ╰─ Constant(Int(10))

Workflow Builder:
ShapePreservingBuilder
├─ ShapePreservingBuilder
│  ├─ ShapePreservingBuilder
│  │  ├─ ShapePreservingBuilder
│  │  │  ├─ CollectionBuilder(Root())
│  │  │  │  ├─ $ReadF(test; zips)
│  │  │  │  ╰─ Schema
│  │  │  ├─ \&/(Both)
│  │  │  │  ├─ JsCore(_.loc)
│  │  │  │  ╰─ ExprOp("$loc")
│  │  │  ╰─ Chain
│  │  │     ├─ $ReadF(; )
│  │  │     ╰─ $MatchF
│  │  │        ╰─ Doc
│  │  │           ╰─ Expr($_0 -> ElemMatch(\/-(Exists(true))))
│  │  ├─ \&/(Both)
│  │  │  ├─ JsCore(_.pop < _.loc[1])
│  │  │  ╰─ ExprOp({
│  │  │            "$lt": ["$pop", { "$arrayElemAt": ["$loc", { "$literal": NumberInt("1") }] }]
│  │  │          })
│  │  ╰─ Chain
│  │     ├─ $ReadF(; )
│  │     ╰─ $MatchF
│  │        ╰─ Doc
│  │           ╰─ Expr($_0 -> Eq(Bool(true)))
│  ├─ \&/(Both)
│  │  ├─ JsCore(_._id)
│  │  ╰─ ExprOp("$_id")
│  ╰─ Chain
│     ├─ $ReadF(; )
│     ╰─ $SortF
│        ╰─ SortKey(_0 -> Ascending)
╰─ Chain
   ├─ $ReadF(; )
   ╰─ $LimitF(10)

Workflow (raw):
Chain
├─ $ReadF(test; zips)
├─ $MatchF
│  ╰─ Doc
│     ╰─ Expr($loc -> ElemMatch(\/-(Exists(true))))
├─ $ProjectF
│  ├─ Name("0" -> {
│  │       "$lt": ["$pop", { "$arrayElemAt": ["$loc", { "$literal": NumberInt("1") }] }]
│  │     })
│  ├─ Name("src" -> "$$ROOT")
│  ╰─ ExcludeId
├─ $MatchF
│  ╰─ Doc
│     ╰─ Expr($0 -> Eq(Bool(true)))
├─ $SortF
│  ╰─ SortKey(_id -> Ascending)
├─ $LimitF(10)
╰─ $ProjectF
   ├─ Name("__quasar_mongodb_sigil" -> "$src")
   ╰─ ExcludeId

Workflow (crystallized):
Chain
├─ $ReadF(test; zips)
├─ $MatchF
│  ╰─ Doc
│     ╰─ Expr($loc -> ElemMatch(\/-(Exists(true))))
├─ $ProjectF
│  ├─ Name("0" -> {
│  │       "$lt": ["$pop", { "$arrayElemAt": ["$loc", { "$literal": NumberInt("1") }] }]
│  │     })
│  ├─ Name("src" -> "$$ROOT")
│  ╰─ ExcludeId
├─ $MatchF
│  ╰─ Doc
│     ╰─ Expr($0 -> Eq(Bool(true)))
├─ $SortF
│  ╰─ SortKey(_id -> Ascending)
├─ $LimitF(10)
╰─ $ProjectF
   ├─ Name("__quasar_mongodb_sigil" -> "$src")
   ╰─ ExcludeId

MongoDB:
db.zips.aggregate(
  [
    { "$match": { "loc": { "$elemMatch": { "$exists": true } } } },
    {
      "$project": {
        "0": {
          "$lt": [
            "$pop",
            { "$arrayElemAt": ["$loc", { "$literal": NumberInt("1") }] }]
        },
        "src": "$$ROOT",
        "_id": false
      }
    },
    { "$match": { "0": true } },
    { "$sort": { "_id": NumberInt("1") } },
    { "$limit": NumberLong("10") },
    { "$project": { "__quasar_mongodb_sigil": "$src", "_id": false } }],
  { "allowDiskUse": true });
```
</details>

It looks like the `_id` here is tripping up the query:
```
    {
      "$project": {
        "0": {
          "$lt": [
            "$pop",
            { "$arrayElemAt": ["$loc", { "$literal": NumberInt("1") }] }]
        },
        "src": "$$ROOT",
        "_id": false
      }
    },
```
Without `"_id": false` the query sorts ok. Not sure yet how to resolve this though.

**Comment by rintcius** [comment]
@djspiewak can you restart Appveyor for me? I heard you are the admin for it. The job timed out.

**Comment by alissapajer** [comment]
@djspiewak what would it take to give us all permission to restart jobs?

**Comment by djspiewak** [comment]
@rintcius Restarted.  The timeout is concerning though.  That's a considerably longer build than PRs normally require.

@alissapajer To my knowledge, it isn't possible.  I've asked @zeeiyerWork to liaise with AppVeyor to get our build moved over to an org account, so that it works a bit more like Travis.  For now, I guess I'm just the bottleneck.  :-/

**Comment by rintcius** [comment]
@djspiewak thanks! - yeah hopefully not something that happens often

**Comment by zeeiyerWork** [comment]
waiting on appveyor - sent reminder. (2 concurrent jobs + move to build@slamdata.com)

**Pull request merged**
