### PR TITLE
Enable many integration tests for spark.

### PR DESCRIPTION
**Pull request by alissapajer**
Enable many integration tests for spark.

### CODE REVIEW

**Comment by rabbitonweb** [comment]
@alissapajer can you specify which tests (that are marked as `pending`) are failing because of some spark related issue (not qscript related)

**Comment by alissapajer** [comment]
@rabbitonweb will do. I'll update PR with comments in the `.test` files.

**Comment by alissapajer** [comment]
@rabbitonweb added comments for all the known `QScript` issues. I haven't looked at the `QScript` for all the failing test, so there could be more issues still to report.

**Comment by rabbitonweb** [comment]
LGTM - I will merge once travis is happy

**Pull request merged**
