### PR TITLE
mongo mimir conflict

### PR DESCRIPTION
**Pull request by rabbitonweb**

### CODE REVIEW

**Comment by rabbitonweb** [comment]
@nicflores please have a look if it solved the problem

**Comment by alissapajer** [comment]
This does not fix the bug for me locally. When I start the REPL against this PR, I still get `Error: No configuration setting found for key 'akka'`.

**Comment by nicflores** [comment]
If you have a mongo mount and you run `web/run` and then curl to add a mimir mount we get the following error:

```
nicandroflores @ ~/Documents/github
 [74] → curl -v -X PUT http://localhost:20223/mount/fs/mimir/ -d '{ "mimir": { "connectionUri": "/Applications/SlamData Advanced 4.3.0-prerelease-5.app/Contents/Resources/app/local/" } }'
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 20223 (#0)
> PUT /mount/fs/mimir/ HTTP/1.1
> Host: localhost:20223
> User-Agent: curl/7.51.0
> Accept: */*
> Content-Length: 120
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 120 out of 120 bytes
< HTTP/1.1 500 Physical filesystem error.
< Content-Type: application/json; charset=UTF-8
< Date: Wed, 25 Oct 2017 23:19:46 GMT
< Content-Length: 129
<
* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact
{ "error": { "status": "Physical filesystem error.", "detail": { "message": "No configuration setting found for key 'akka'" } } }
```

**Comment by djspiewak** [comment]
I'm going to merge this, since it's a good change.  It doesn't fix the original bug though.  :-(

**Pull request merged**
