### PR TITLE
Fix REPL debug output.

### PR DESCRIPTION
**Pull request by sellout**
This also eliminates the implicit Show automatically provided by RenderTree.

### CODE REVIEW

**Comment by sellout** [comment]
Grrr … the Travis 49-minute timeout 😕

**Comment by mossprescott** [comment]
LGTM, but needs merge from master now.

**Comment by sellout** [comment]
Merged in master.

**Comment by mossprescott** [comment]
Conflicting now.

**Comment by sellout** [comment]
Ok, come on. No whammies.

**Pull request merged**
