### PR TITLE
Rewrite tests to use QScript DSL

### PR DESCRIPTION
**Pull request by edmundnoble**
Also reduced the use of tuples in `mkDefaults` because it makes the pretty printer more fragile.

### CODE REVIEW

**Comment by edmundnoble** [comment]
@wemrysi It looks like that file's using the DSL too, it was written after the DSL was introduced - maybe the imports are throwing you off. I caught `RewriteNullSpec` in the marklogic connector though, after another pass.

**Comment by wemrysi** [comment]
@edmundnoble Hm, did you see the compile errors for `PlannerQScriptSpec`, that's why I pointed it out.

**Comment by edmundnoble** [comment]
Ahhh no I didn't, thanks.

**Comment by edmundnoble** [comment]
@djspiewak Could you restart appveyor please?

**Comment by alissapajer** [comment]
@edmundnoble ditto what @wemrysi said, thanks for doing all this, our tests are much better for it!

**Pull request merged**
