### PR TITLE
Require callback to initMetaStoreOrStart to handle shutdown

### PR DESCRIPTION
**Pull request by wemrysi**
Fixes an issue where the repl would immediately close all mounts after initialization.

### CODE REVIEW

**Comment by jedesah** [comment]
I can see that this change hands over the responsibility of calling the Quasar shutdown `Task` to the client code. That's less desirable of course, but I imagine there is a good reason, but a glance at the diff does not immediately inform me as to why that's necessary. @wemrysi Would you mind just briefly walking me through what's happening to cause the error @djspiewak  mentioned? Based on the error message, I imagine that shutdown was being called too early. Ah! I think I just figured it out, I guess the "Start the Repl" `Task` is async so we call shutdown before the repl is actually done. I guess it would be preferable to make the start Repl task synchronous but perhaps that is tricky so maybe this is a reasonable compromise to get things working

**Comment by wemrysi** [comment]
Yeah, the previous impl assumed the `Task` returned by the callback to `initMetaStoreOrStart` blocked, which isn't always true.

**Comment by jedesah** [comment]
I feel like we should use `Task.async` to build the Repl `Task` so that it is blocking. That way we wouldn't have to delegate shutdown to the client code. Also, I feel like there are lot's of places in the codebase where we assume that `onFinish` behaves appropriately. I think the fact that `ensuring` is not working as expected in this case is because we are not properly building the `Task`. @wemrysi What do you think?

**Comment by wemrysi** [comment]
Closing in favor of #2578.

**Pull request closed without merging**
