### PR TITLE
Relocate the jawn-based ejson.Json parser to ejson package

### PR DESCRIPTION
**Pull request by wemrysi**

### CODE REVIEW

**Comment by paulp** [comment]
Can this one also be moved? 
```scala
  object JsonParser extends SupportParser[Data] {
    implicit val facade: Facade[Data] =
      new SimpleFacade[Data] {
        def jarray(arr: List[Data])         = Data.Arr(arr)
        def jobject(obj: Map[String, Data]) = Data.Obj(ListMap(obj.toList: _*))
        def jnull()                         = Data.Null
        def jfalse()                        = Data.False
        def jtrue()                         = Data.True
        def jnum(n: String)                 = Data.Dec(BigDecimal(n))
        def jint(n: String)                 = Data.Int(BigInt(n))
        def jstring(s: String)              = Data.Str(s)
      }
  }
```

**Comment by wemrysi** [comment]
@paulp Yessir.

**Comment by wemrysi** [comment]
@paulp Ready for another look.

**Comment by paulp** [comment]
Looks great thanks. I'll merge.

**Pull request merged**
