### PR TITLE
Enable multiple spark connectors

### PR DESCRIPTION
**Pull request by rabbitonweb**
Previously SparkContext was created per connection (per mount). This
had major drawback as only one spark based connector could be mounted
at given moment.
With this change SparkContext will be created only when its needed (during
query/read) and close immediately when result is returned.
This however has consequences - if two different users try to use
connection in the same time, second one will be blocked with an error.
 
Part  of https://github.com/quasar-analytics/quasar/issues/2297

### CODE REVIEW

**Comment by jdegoes** [comment]
This is not a good long-term solution. We can expect many simultaneous queries.

**Comment by rabbitonweb** [comment]
@jdegoes yeah, this is what I wanted to talked to you abgout today. Problems with this approach are in commits comments. 

I will close this PR as I have other approach which I think is lot better.

**Comment by alissapajer** [comment]
@rabbitonweb can this be closed now that #2314 is open?

**Comment by alissapajer** [comment]
@rabbitonweb can we close this issue?

**Comment by rabbitonweb** [comment]
I physically close this issue today in the morning! Wow.. magic... closing it now!

**Pull request closed without merging**
