### PR TITLE
Remove rogue CHANGELOG/revision.md file.

### PR DESCRIPTION
**Pull request by alissapajer**

### CODE REVIEW

**Comment by sellout** [comment]
Should probably move the content into the changelog file created by the #1306 merge?

**Comment by alissapajer** [comment]
@paulp (\cc @sellout) this resolves the conflict in https://github.com/quasar-analytics/quasar/pull/1296

A PR was merged with an old version of the merge script expecting bugfix.md and not revision.md, and both a bugfix.md and a revision.md were present in the PR, so the revison.md file stuck around. (The current version of the merge script expects revision.md).

**Comment by alissapajer** [comment]
@sellout yeah, moving the content over by hand makes sense, I'll do that

**Comment by alissapajer** [comment]
And, this PR will need it's own changelog file too! :)

**Comment by alissapajer** [comment]
We don't actually want this PR to have a changelog though, so we could bypass the merge script in this case and just merge directly to master.

**Comment by sellout** [comment]
@jedesah will probably take me to task for this, but … I think a fix to the changelog should just be merged with the GitHub button.

**Comment by paulp** [comment]
I agree with @alissapajer and @sellout.

**Comment by paulp** [comment]
Also, the CI situation is critical. Waiting for the tests on a PR like this (and like many of the others) makes no sense.

**Comment by alissapajer** [comment]
@paulp this is technically assigned to you - all good if I merge manually? Or you can beat me to it if you want :)

**Comment by jedesah** [comment]
@sellout Haha! 😄 . We are going to use the git commit message for the CHANGELOG soon right!?

**Pull request merged**
