### PR TITLE
backport/v20.14.16+ Preserve query params upon HTTP redirect

### PR DESCRIPTION
**Pull request by drostron**

### CODE REVIEW

**Comment by jedesah** [comment]
LGTM. Github IU is being weird. Either because of my slow connection or because it's not master.

**Comment by drostron** [comment]
@jr not sure about the UI, but I'm looking into the build failure.

**Comment by drostron** [comment]
@jedesah Ready

**Comment by jedesah** [comment]
@drostron Looks like the merge script doesn't like this PR because of the name of the branch it wants to merge into?

Could you bump the version manually perhaps?

**Comment by drostron** [comment]
@jedesah Merged per your request due to something getting in the way from your side at the moment.

**Pull request merged**
