### PR TITLE
[WIP] Fix Cassandra integration tests

### LINKED ISSUE #2718: Passing integration tests for spark-cassandra

### PR DESCRIPTION
**Pull request by rabbitonweb**
Seemed to fix #2718 before the merge. Now with dyncamic loading, I can not really say, as the whole spark is pretty much disabled. Opening PR nevertheless

### CODE REVIEW

**Comment by djspiewak** [comment]
This needs an assignee

**Comment by alissapajer** [comment]
@djspiewak I think we should keep this on hold (unmerged) until the spark travis build is back online. Unless @rabbitonweb has reason to merge it sooner?

**Comment by rabbitonweb** [comment]
I've opened PR but it should be labeled wip

**Comment by rabbitonweb** [comment]
Which can not be done from mobile phone apparently :) I will add WIP to it once near computer

**Comment by alissapajer** [comment]
@rabbitonweb how much work is left before we can get this reviewed and merged? It looks like a handful of cassandra tests failed the last travis build. Could we just skip or pending those and then get this landed? And then we can open individual issues for any tests that are failing when they shouldn't be.

**Comment by rabbitonweb** [comment]
@alissapajer I was thinking about this the other day. Cassandra is really failing on CI right now. I know how to fix it, but cassandra got low priority. I will try one more attempt with fixing the interpeter on Monday. If I fail, I make failing tests pending and remove WIP from this

**Comment by rabbitonweb** [comment]
will get back to this after postgres is ready

**Pull request closed without merging**
