### PR TITLE
[Blocked] Upgrade `refined` to version `0.6.1`

### PR DESCRIPTION
**Pull request by jedesah**

### CODE REVIEW

**Comment by jedesah** [comment]
Dammit, I forgot about the `scalacheck` issue

**Comment by jedesah** [comment]
This is blocked on quasar being updated to `scalacheck` version `1.13.x`.

**Comment by sellout** [comment]
Oooh, this should be unblocked now, right?

**Comment by jedesah** [comment]
Yep! I'll resolve the conflicts and push a new commit tmr! 🎆

**Comment by sellout** [comment]
Oh, heh, I guess it was already done 😄

**Comment by jedesah** [comment]
Haha! yea!

**Pull request closed without merging**
