### PR TITLE
Add `flakyTest` marker to "download as zipped directory" tests

### PR DESCRIPTION
**Pull request by jedesah**

### CODE REVIEW

**Comment by drostron** [comment]
👍🏽, will merge upon successful build.

**Comment by jedesah** [comment]
@drostron Have you seen this failure before?

**Comment by drostron** [comment]
@jedesah Looks similar to https://github.com/quasar-analytics/quasar/issues/1295#issuecomment-238974457

**Comment by jedesah** [comment]
Okay, well, I guess I'll start it again.

**Pull request merged**
