### PR TITLE
Migrate some `quasar.effect` related code from Quasar Advanced

### PR DESCRIPTION
**Pull request by jedesah**

### CODE REVIEW

**Comment by wemrysi** [comment]
@jedesah So I don't have to compare, is the new `Read` just a verbatim copy from advanced?

**Comment by wemrysi** [comment]
Also, thanks for doing this, something I can cross of my list!

**Comment by jedesah** [comment]
Yup! Verbatim copy!

**Comment by wemrysi** [comment]
:

**Pull request closed without merging**
