### PR TITLE
remove the last two uses of shapeless's deriveEqual

### PR DESCRIPTION
**Pull request by mossprescott**
This improves incremental compile time for the two files involved (workflowbuilder and logicalplan) by from about 100s to less than 10s.

From-scratch compile time is reduced by about 50% for me.

Will try to confirm some improvement in Travis before merging.

### CODE REVIEW

**Comment by sellout** [comment]
Nice. Hopefully we’ll be able to use deriving more consistently and with less performance hit with export-hook, or when Typeclassic is a thing.

**Comment by mossprescott** [comment]
Looks like this is saving about a minute or so in each build in Travis. Building again after finding a line of debug code I've been meaning to clean up...

**Comment by drostron** [comment]
👍🏽

**Comment by mossprescott** [comment]
Merged via the script.

**Pull request closed without merging**
