### PR TITLE
Merge master into qsu

### PR DESCRIPTION
**Pull request by alissapajer**

### CODE REVIEW

**Comment by jsantos17** [comment]
@alissapajer would you mind adding the last changes from `master` to this? I need them to fix more Mongo tests. I just merged #3138

**Comment by djspiewak** [comment]
@jsantos17 I'll do a fresh merge from master and will close this PR.

**Comment by alissapajer** [comment]
@djspiewak were you going to open a new PR with a merge from master? I didn't see a new one opened.

**Comment by djspiewak** [comment]
@alissapajer I just did a direct merge and push, since it was the same as your PR with a couple more commits.

**Pull request closed without merging**
