### PR TITLE
QSU: Comment out debug printlns and localize required imports.

### PR DESCRIPTION
**Pull request by alissapajer**

### CODE REVIEW

**Comment by djspiewak** [comment]
I did this with a separate function in my PR menagerie so that I didn't have to constantly re-comment imports.  Either way is fine with me though.

**Comment by alissapajer** [comment]
Ah, yeah I'm fine with either way as well. In your PR there is only a single line to uncomment in order to debug, so maybe that's better?

**Comment by djspiewak** [comment]
@alissapajer That's what I was thinking.  It's at least more convenient for now.

**Comment by wemrysi** [comment]
Closing in favor of https://github.com/quasar-analytics/quasar/pull/3139/commits/3eb706cd10baa90b8d11bcc0ea1ab1bfa7cca871

**Pull request closed without merging**
