### PR TITLE
Fix test failure in Spark `PlannerSpec`

### PR DESCRIPTION
**Pull request by jedesah**
Failure was caused by `NonEmptyList` not being `Serializable`. Fix was to avoid having `NonEmptyList` be inside of a "Spark closure", i.e. call `toList` outside of the closure.

### CODE REVIEW

**Comment by paulp** [comment]
I guess we have no better way to find out about serialization problems than seeing tests fail in spark after the fact? In that case, nothing to argue with here.

**Comment by jedesah** [comment]
Agreed. Getting Spark tests to run on Travis should be pretty high priority.

Anything else I need to do for you to merge this?

**Comment by rabbitonweb** [comment]
Hmm, am I missing something here. PlannerSpec was failing?

**Comment by jedesah** [comment]
@rabbitonweb Yes. You haven't noticed it locally?

**Comment by rabbitonweb** [comment]
I was fixing this on separate branch, but I'm surprised PlannerSpec was failing.

**Comment by paulp** [comment]
@jedesah I'll merge it.

**Comment by rabbitonweb** [comment]
@jedesah yeah, i'm 100% sure it was working... CI is needed more then ever

**Comment by paulp** [comment]
I attempted to merge this back when I said that, but only just now came back to the tab where it failed over a conflict involving `CHANGELOG/revision.md`.

**Comment by jedesah** [comment]
So I just merged in `master`. Hopefully that fixes the conflict that was happening with the merge script.

I didn't actually run into any conflict locally though...

**Comment by paulp** [comment]
Worked this time. Who knows.

**Pull request merged**
