### PR TITLE
Add coursier plugin to project

### PR DESCRIPTION
**Pull request by rabbitonweb**
Coursier works as a plugin for a SBT project. Coursier is a super fast
dependency resolver that allows fetching the dependencies
in parallel.

More about the plugin here: https://github.com/alexarchambault/coursier

### CODE REVIEW

**Comment by rabbitonweb** [comment]
It fails on a single build MONOGO_RELEASE_3_0_RO - I truly don't know why.

**Comment by jedesah** [comment]
So is the build passing now?

**Comment by jedesah** [comment]
I don't have any objections to this if it works on Travis. The question arises as to whether this should be installed by each developer since in theory it doesn't really affect the semantics of the build. However, it probably makes sense to add it to the project if we want to commit to making sure the build works with this plugin even if bugs/issues pop up in the future.

Also, if this makes our builds faster (especially on Travis) then 💃  💃  💃 . And that would be a pretty strong argument for adding it the project's build.

**Comment by jedesah** [comment]
The travis build times though are pointing towards this not being faster. It was actually a little slower than the previous PR. I wonder why that is?

**Comment by jedesah** [comment]
As @sellout pointed out at lunch, slower build times are probably due to Travis instances only having 1.5 cores. My vote would be to wait until we have a beefier build machine before making use of this plugin.

**Comment by jedesah** [comment]
Unless there are any objections, I am going to go ahead and close this PR as it's a really neat idea but it's not really practical for us right now.

**Pull request closed without merging**
