### PR TITLE
Tidy-up build dependencies

### PR DESCRIPTION
**Pull request by jedesah**

### CODE REVIEW

**Comment by jedesah** [comment]
> File name too long

Excited to diagnose how this change triggered that scalac error...

**Comment by jedesah** [comment]
@paulp Any idea what might be causing the compile error? I tried shuffling bits around to see if that might help (never know!) but otherwise I am at a loss for how this change is suddenly triggering a "File name too long" error. I have heard that you have experience with such errors :smile:

**Comment by paulp** [comment]
Can it involve monocle-macro somehow? I can't see any other way to connect this change to that error. Is the failure reproducible outside of travis?

**Comment by paulp** [comment]
It is reproducible outside travis, so maybe I'll know what's going on soon.

**Comment by jedesah** [comment]
It could be `monocle-macro`. It's odd though because `monocle-macro` was already in the classpath, we only subtracted stuff from the classpath.

**Comment by paulp** [comment]
You subtract something from the classpath, and now all the transitive dependencies it was bringing in go away. For instance monocle-macro depends on scalaz 7.2.8, which evicts 7.2.4 everywhere it appears. With this change those subprojects go back to using 7.2.4

**Comment by paulp** [comment]
The too long filename is `mongodb/target/scala-2.11/classes/quasar/physical/mongodb/planner/MongoDbPlanner$$nestedInAnonfun$quasar$physical$mongodb$planner$MongoDbPlanner$$exprCheck$1$1$lambda$$quasar$physical$mongodb$planner$MongoDbPlanner$$nestedInAnonfun$quas` or at least that's the amount visible via opensnoop. I haven't figured out why it only occurs after this change.

**Comment by paulp** [comment]
Some difference in the dependencies may trigger different behavior by scalac during trait mixin and make it decide it has to fully qualify some names where it didn't before.

**Comment by paulp** [comment]
Just using a string to limit the length of these lists, the classfiles created in master which contain `MongoDbIOWorkflowExecutor` are
```
mongodb/MongoDbIOWorkflowExecutor$$anon$1.class
mongodb/MongoDbIOWorkflowExecutor$$anon$1.class
mongodb/MongoDbIOWorkflowExecutor$.class
mongodb/MongoDbIOWorkflowExecutor$.class
mongodb/MongoDbIOWorkflowExecutor.class
mongodb/MongoDbIOWorkflowExecutor.class
```
Whereas with this change, 63 classfiles are created, the first few of which are
```
mongodb/MongoDbIOWorkflowExecutor$$anon$1.class
mongodb/MongoDbIOWorkflowExecutor$$nestedInAnon$1$lambda$$apply$1.class
mongodb/MongoDbIOWorkflowExecutor$$nestedInAnon$1$lambda$$apply$1.class
mongodb/MongoDbIOWorkflowExecutor$$nestedInAnon$1$lambda$$quasar$physical$mongodb$MongoDbIOWorkflowExecutor$$nestedInAnon$1$$$nestedInAnonfun$26$1.class
mongodb/MongoDbIOWorkflowExecutor$$nestedInAnon$1$lambda$$quasar$physical$mongodb$MongoDbIOWorkflowExecutor$$nestedInAnon$1$$$nestedInAnonfun$26$1.class
mongodb/MongoDbIOWorkflowExecutor$$nestedInAnon$1$lambda$$quasar$physical$mongodb$MongoDbIOWorkflowExecutor$$nestedInAnon$1$$$nestedInAnonfun$26$2.class
mongodb/MongoDbIOWorkflowExecutor$$nestedInAnon$1$lambda$$quasar$physical$mongodb$MongoDbIOWorkflowExecutor$$nestedInAnon$1$$$nestedInAnonfun$26$2.class
mongodb/MongoDbIOWorkflowExecutor$$nestedInAnon$1$lambda$$quasar$physical$mongodb$MongoDbIOWorkflowExecutor$$nestedInAnon$1$$$nestedInAnonfun$26$3.class
mongodb/MongoDbIOWorkflowExecutor$$nestedInAnon$1$lambda$$quasar$physical$mongodb$MongoDbIOWorkflowExecutor$$nestedInAnon$1$$$nestedInAnonfun$26$3.class
mongodb/MongoDbIOWorkflowExecutor$$nestedInAnon$1$lambda$$quasar$physical$mongodb$MongoDbIOWorkflowExecutor$$nestedInAnon$1$$$nestedInAnonfun$26$4.class
```

**Comment by paulp** [comment]
I verified that dropping `-Ydelambdafy:method` from the compiler options makes this problem go away. The relevant compiler code is a mess which I cannot unravel well enough to make a more targeted suggestion.

**Comment by jedesah** [comment]
@paulp Wow! That is some in depth analysis.

I was tempted to remove `-Ydelambdafy:method` but in the end I seem to have been able to side-step the issue by upgrading monocle. It adds an eviction warning, but that should go away once `matryoshka` is upgraded.

**Pull request merged**
